apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: microbank-dev
  labels:
    app: api-gateway
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 80    # Keeping port 80 for abstracting the actual port
    targetPort: 8123

