spring:
  application:
    name: document-service

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.microbank.local/realms/microbank
          jwk-set-uri: http://auth.microbank.local/realms/microbank/protocol/openid-connect/certs

management:
  server:
    port: 8084
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

