spring:
  application:
    name: document-service

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.dev.microbankapp.com/realms/microbank
          jwk-set-uri: http://auth.dev.microbankapp.com/realms/microbank/protocol/openid-connect/certs

server:
  port: ${SERVER_PORT:8084}        

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8094}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

