spring:
  application:
    name: notification-service

  mail:
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

management:
  server:
    port: 8085
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
