spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: transaction-service
          uri: http://transaction-service.microbank-transaction.svc.cluster.local
          predicates:
             - Path=/api/v1/transactions/**

        - id: auth-service
          uri: http://auth-service.microbank-auth.svc.cluster.local
          predicates:
            - Path=/api/v1/auth/**

        - id: account-service
          uri: http://account-service.microbank-account.svc.cluster.local
          predicates:
            - Path=/api/v1/accounts/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.dev.microbankapp.com/realms/microbank
          jwk-set-uri: http://auth.dev.microbankapp.com/realms/microbank/protocol/openid-connect/certs

server:
  port: ${SERVER_PORT:8123}

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8124}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

