server:
  port: 8123

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: transaction-service
          uri: http://transaction-service
          predicates:
             - Path=/api/v1/transactions/**

        - id: auth-service
          uri: http://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: account-service
          uri: http://account-service
          predicates:
            - Path=/api/v1/accounts/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.microbank.local/realms/microbank
          jwk-set-uri: http://auth.microbank.local/realms/microbank/protocol/openid-connect/certs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

