apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-document
  namespace: microbank-dev
  labels:
    app: postgres-document
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-document
  template:
    metadata:
      labels:
        app: postgres-document
    spec:
      containers:
      - name: postgres
        image: postgres:17-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: document_db
        - name: POSTGRES_USER
          value: document_db
        - name: POSTGRES_PASSWORD
          value: document_db