spring:
  application:
    name: transaction-service

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.dev.microbankapp.com/realms/microbank
          jwk-set-uri: http://auth.dev.microbankapp.com/realms/microbank/protocol/openid-connect/certs

management:
  server:
    port: 8083
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.server: DEBUG
