apiVersion: v1
kind: Service
metadata:
  name: maildev
  namespace: microbank-dev
spec:
  selector:
    app: maildev
  ports:
  - name: smtp
    port: 1025
    targetPort: 1025
  - name: ui
    port: 1080
    targetPort: 1080
