apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: microbank-dev
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        imagePullPolicy: Always
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        env:
        - name: MINIO_ROOT_USER
          value: capellax
        - name: MINIO_ROOT_PASSWORD
          value: "12345678"
        ports:
        - containerPort: 9000   # API
        - containerPort: 9001   # Console
